//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace small_coaching_management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Schedule
    {
        public int ScheduleId { get; set; }
        [Display(Name ="Class Time")]
        public System.DateTime ClassTime { get; set; }
        [Display(Name ="Class Day")]
        public string Class_Day { get; set; }
        [Display(Name ="Teacher Name ")]
        public int TeacherId { get; set; }
        [Display(Name ="Class")]
        public int ClassId { get; set; }
        [Display(Name ="Course")]
        public int CourseId { get; set; }

        public virtual Class Class { get; set; }
        public virtual Course Course { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
