//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace small_coaching_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentBill()
        {
            this.Transcetions = new HashSet<Transcetion>();
        }
    
        public int StudentBilId { get; set; }
        public string BillMonth { get; set; }
        public int Amount { get; set; }
        public int StudentId { get; set; }
    
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transcetion> Transcetions { get; set; }
    }
}
